services:
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    environment:
      - PGRST_DB_URI=postgres://usuario:senha@postgres:5432/postgrest
      - PGRST_DB_SCHEMA=api
      - PGRST_DB_ANON_ROLE=web_anon
      - PGRST_SERVER_PORT=3000
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - ./postgres-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgrest
    command: ["postgres", "-c", "log_statement=all"]  # override entrypoint command with log_statement argument
    ports:
      - "5432:5432"
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    
